document:
  name: Portale delle segnalazioni
  description: |
    Il Portale delle segnalazioni è la piattaforma dell'Autorità per le garanzie nelle comunicazioni
  tags:
    - Portale delle segnalazioni
    - Consumatori
